name: Publish liflig logging package to GitHub Packages
on:
  push:
    branches:
      - 'master'
defaults:
  run:
    shell: bash
jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: |
          major_version="$(sed -n "s/^.*<major-version>\([0-9]\{1,\}\)<\/major-version>.*$/\1/p" pom.xml)"
          date="$(date -u "+%Y%m%d.%H%M%S")"
          tag="$major_version.$date"
          mvn --batch-mode deploy -Drevision="$tag" -Dtag="$tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
